### ISSUE TITLE
Tree selection styling no longer covers the entire folder name on overflow

### ISSUE THREAD

**Issue by dkilgore** [ExactTarget/fuelux-mctheme#172]
![screen shot 2015-02-18 at 1 31 56 pm](https://cloud.githubusercontent.com/assets/1205242/6253863/8c75a76e-b772-11e4-8fb5-1fc5e0e9bb9f.png)

**Comment by interactivellama** [comment]
I've been able to duplicate. The only way I've been able to fix it is dynamically set a width on the tree. It's the `UL` and it's block level children that are causing the problem.

When we started on the theme. I really wish we could have implementing something like this:
![screen shot 2015-02-18 at 2 44 18 pm](https://cloud.githubusercontent.com/assets/1290832/6255269/e1a60c92-b77c-11e4-9105-57efec344027.png)

With inline selection (and it's how Tree is set up in Fuel UX proper, because of this very issue):
![screen shot 2015-02-18 at 2 48 24 pm](https://cloud.githubusercontent.com/assets/1290832/6255320/34b2f72e-b77d-11e4-898d-fe13def2b687.png)

**Comment by interactivellama** [comment]
@jamin-hall How is this?

![screen shot 2015-03-13 at 3 54 23 pm](https://cloud.githubusercontent.com/assets/1290832/6646230/4d45ce32-c999-11e4-83c1-411285e75d74.png)

**Comment by jaminhall** [comment]
Looks good. Thanks.

**Comment by swilliamset** [comment]
How does this look when selecting a folder?

**Comment by jamin-hall** [comment]
![tree example](https://cloud.githubusercontent.com/assets/10441534/6688227/258b86ec-cc88-11e4-8baa-21975eb3da13.png)

For reference it should look like the attached screenshot. The background highlight should surround the folder icon, but not the expand/collapse icon. This way the user can expand/collapse without selecting/deselecting.

@interactivellama, is there somewhere I can verify this is implemented correctly?
