### ISSUE TITLE
Compiling fuelux-mctheme into custom build theme.

### ISSUE THREAD

**Issue by jbarngr** [ExactTarget/fuelux-mctheme#218]
I pulled this via Bower. When I try to import the fuelux-mctheme/less/fuelux-mctheme.less file in I get an error stating that icons/icons-svg.less cannot be found. I noticed that in the bower download the less/icons folder is not brought down. That is because in bower you tell it not to download any icons folder.

**Comment by interactivellama** [comment]
Thanks @jbarngr. We haven't done extensive testing of ingesting the LESS files directly into apps.

Are you also pulling in Bootstrap's LESS files and outputting all that into one CSS file, too, instead of concatenating the CSS from the dist folder?

**Comment by jbarngr** [comment]
@interactivellama the issue is the bower install of the theme. 
![screen shot 2015-03-31 at 11 51 31 am](https://cloud.githubusercontent.com/assets/915237/6922887/5262bc48-d79c-11e4-9725-7c1f7480f3b1.png)
I have highlights the bad line. In bower.json, like git, the ignore strings are greedy. That means any folder that is named icons will be ignored. To not down load the icons folder that is in the root of the git repo you need to change it to "/icons". That is make it look all at top level folders vs going all the way through the folder structure.

**Comment by chriscorwin** [comment]
> I get an error stating that icons/icons-svg.less cannot be found.

That file is actually created by Grunt—and then heavily regexified—during the icon build process.

You can read more about this process here:

https://github.com/ExactTarget/fuelux-mctheme/blob/master/icons/Making-Icons.md


As @interactivellama has hinted at, the theme's .less files aren't really to be used "raw" — but truly are to be compiled into .css.

If you're doing _active development_ on the theme itself (one reason I can think of that you're attempting to use the .less files directly), you may wish to look into the `$ grunt servedev` task: this will watch the .less files for changes and (along with livereload) automagically refresh your document in the browser when the new .css file is created.

You can add: `	<script src="//localhost:35731/livereload.js"></script>` to the file you're working on, and point the css you load in it at `dist/css/fuelux-mctheme-dev.css` instead of `dist/css/fuelux-mctheme.css`.

If you happen to use Google Chrome, you can even set up your developer tools to use [workspaces](https://developer.chrome.com/devtools/docs/workspaces) and have direct access to the .less files for editing right there.

If you have any questions, feel free to reach out to me directly. :)

**Comment by interactivellama** [comment]
@chriscorwin I think @jbarngr is saying that `less/icons' folder is not being downloaded which it should, since it's in the `less folder`.

**Comment by chriscorwin** [comment]
I'm not sure why we have that in the bower ignore _at all_. 

I think we can just rip it out, yo.

**Comment by interactivellama** [comment]
It's in there because I didn't want the AI file and source SVGs, etc to be downloaded via bower.

**Comment by chriscorwin** [comment]
O™

**Comment by interactivellama** [comment]
PR made.

@jbarngr Could you answer my original question: Are you also pulling in Bootstrap's LESS files and outputting all that into one CSS file, too, instead of concatenating the CSS from the dist folder?

I ask because we are trying to determine how MCtheme is being ingested. What teams try first, etc? For instance, if bootstrap.less and fuelux.less and fuelux-mctheme.less all get merged together, there may be variable collisions.

**Comment by jbarngr** [comment]
I am pulling in bootstraps LESS and then the MCTheme and then finally my custom LESS with the .fuelux namespace on my items.

**Comment by interactivellama** [comment]
Are you pulling in `fuelux/less/fuelux.less` also?

**Comment by jbarngr** [comment]
Yes.

Jeremy Barngrover
cell: (219) 954-0023

**Comment by interactivellama** [comment]
@jbarngr Fix has been merged in. Release is not scheduled to occur until next week. Feel free to use #master, but `/dist` is always built up to date.
