### ISSUE TITLE
Verify that all the LESS come together (bootstrap, Fuel UX, and MCtheme) 

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux-mctheme#220]
> Here come old flattop. He come grooving up slowly
> He got ju-ju eyeballs. He's one holy roller
> He got hair down to his knees
> Got to be a joker he just do what he please...

Possibly a temp build that gets git ignored? We currently have no plans to maintain an additional bundled CSS file in `/dist`, but do need to insure that all our LESS plays nice with each other.

**Comment by swilliamset** [comment]
:+1: beatles

**Comment by interactivellama** [comment]
Until this is changed, the best way to use Bootstrap, Fuel UX and MCtheme LESS files together are to import the compiled CSS files.

`@import 'bower_components/bootstrap/dist/css/bootstrap.css`
`@import 'bower_components/fuelux/dist/css/fuelux.css`
`@import 'bower_components/fuelux-mctheme/dist/css/fuelux-mctheme.css`

**Comment by cormacmccarthy** [comment]
Note that this will require some manual movings of font files: https://github.exacttarget.com/IMHDev/mc-automation-studio/blob/jfv-2015-04/development.md#css

## CSS
Getting to just one CSS file is slightly complicated by the fact that bootstrap and fuelux libraries were not really intended to be used this way. You will need to include them in your [base less](#compiling-less) file, as well as [copying the fonts](#copying-fonts) to the proper places.

### Compiling LESS
Place the following at the top of your root LESS file (adjusting the paths to fit your particular setup):

```CSS
@import (less) "../vendor/bootstrap/css/bootstrap.css";
@import (less) "../vendor/fuelux3/css/fuelux.css";
@import (less) "../vendor/fuelux-mctheme/css/fuelux-mctheme.css";
```

### Copying Fonts
Because of the way Bootstrap and Fuel UX libraries relatively link to fonts, in order to have just one CSS file, you have to copy the font files to the appropriate place (for the relative linking to work). The following are [grunt config settings](#grunt) that will work with `grunt-contrib-copy`

```Javascript
copy: {
    bsfonts: {
        files: [{
            expand: true
            , flatten: true
            , src: './dev/vendor/fuelux3/fonts/*'
            , dest: '<%= config.tmpDir %>Dynamic/fonts/'
        }]
    }
    , fxfonts: {
        files: [{
            expand: true
            , flatten: true
            , src: './dev/vendor/bootstrap/fonts/*'
            , dest: '<%= config.tmpDir %>Dynamic/fonts/'
        }]
    }
    ,bsfontsdev: {
        files: [{
            expand: true
            , flatten: true
            , src: './dev/vendor/fuelux3/fonts/*'
            , dest: './<%= config.rJsDir %>fonts/'
        }]
    }
    , fxfontsdev: {
        files: [{
            expand: true
            , flatten: true
            , src: './dev/vendor/bootstrap/fonts/*'
            , dest: './<%= config.rJsDir %>fonts/'
        }]
    }
}
```

##### The Single Style Tag
```HTML
    <link rel="stylesheet" type="text/css" href="css/styles.css" />
```

###### grunt-watch
You will probably want to set up a [grunt-watch](#grunt-watch) task to compile your single CSS file on the fly to simplify development.
```Javascript
watch: {
    less: {
        files: [ '**/*.less' ]
        , tasks: [ 'less' ]
    },
}
```

**Comment by cormacmccarthy** [comment]
No plans to do this. How to do it is documented here if anyone wants/needs it.
